#!/bin/bash

# created to generate symbolic links to 4D fMRI files (helpful for saving memory)

copydir= #insert path to copy the data to
datadir= #insert path to copy the data from (subject level)
cd $datadir
subjectlist=$(ls --ignore={"*.html","*.txt","*.json","*.tsv","logs"}) #grab subjects

for subject in $subjectlist; do
	if [ ! -e $datadir/"$subject"/func/"$subject"_task-visualrun01_space-MNI152NLin6Asym_res-2_desc-preproc_bold_tproj_hipass01_aCompCor6par6_sm6mm_masked.nii.gz ]; then
		echo ""$subject" visualrun01 doeasn't exist in data directory" #example file format here
	elif [ -e $datadir/"$subject"/func/"$subject"_task-visualrun01_space-MNI152NLin6Asym_res-2_desc-preproc_bold_tproj_hipass01_aCompCor6par6_sm6mm_masked.nii.gz ]; then
	ln -s $datadir/"$subject"/func/"$subject"_task-visualrun01_space-MNI152NLin6Asym_res-2_desc-preproc_bold_tproj_hipass01_aCompCor6par6_sm6mm_masked.nii.gz $copydir
	fi
done
